In [1]:
# pip install kagglehub

In [3]:
import pandas as pd
import numpy as np
import matplotlib
import seaborn as sns
import sklearn

https://www.kaggle.com/datasets/vipulshinde/incident-response-log

Attribute Information:

1. number: идентификатор инцидента (24 918 различных значений);
2. incident state: восемь уровней, контролирующих переход процесса управления инцидентами от открытия к закрытию дела;
3. active: логический атрибут, показывающий, активна ли запись или закрыта/отменена;
4. reassignment_count: количество раз, когда в инциденте менялась группа или аналитики поддержки;
5. reopen_count: количество раз, когда решение инцидента было отклонено вызывающим абонентом;
6. sys_mod_count: количество обновлений инцидентов до этого момента;
7. made_sla: логический атрибут, показывающий, превысил ли инцидент целевой SLA;
8. caller_id: идентификатор затронутого пользователя;
9. opened_by: идентификатор пользователя, сообщившего об инциденте;
10. opened_at: дата и время открытия пользователя инцидента;
11. sys_created_by: идентификатор пользователя, зарегистрировавшего инцидент;
12. sys_created_at: дата и время создания системы инцидента;
13. sys_updated_by: идентификатор пользователя, обновившего инцидент и сгенерировавшего текущую запись журнала;
14. sys_updated_at: дата и время обновления системы инцидента;
15. contact_type: категориальный атрибут, показывающий, каким образом был сообщен инцидент;
16. location: идентификатор местоположения затронутого места;
17. category: описание затронутой услуги первого уровня;
18. subcategory: описание затронутой услуги второго уровня (относящееся к описанию первого уровня, т. е. к категории);
19. u_symptom: описание восприятия пользователем доступности услуги;
20. cmdb_ci: идентификатор (элемент подтверждения), используемый для сообщения о затронутом элементе (не обязательно);
21. impact: описание воздействия, вызванного инцидентом (значения: 1: Высокое; 2: Среднее; 3: Низкое);
22. urgency: описание срочности, о которой сообщил пользователь для разрешения инцидента (значения: 1: Высокая; 2: Средняя; 3: Низкая);
23. priority: рассчитывается системой на основе «воздействия» и «срочности»;
24. assignment_group: идентификатор группы поддержки, ответственной за инцидент;
25. assigned_to: идентификатор пользователя, ответственного за инцидент;
26. knowledge: логический атрибут, показывающий, использовался ли документ базы знаний для разрешения инцидента;
27. u_priority_confirmation: логический атрибут, показывающий, было ли дважды проверено поле приоритета;
28. notify: категориальный атрибут, показывающий, были ли сгенерированы уведомления об инциденте;
29. problem_id: идентификатор проблемы, связанной с инцидентом;
30. rfc: (запрос на изменение) идентификатор запроса на изменение, связанного с инцидентом;
31. vendor: идентификатор поставщика, ответственного за инцидент;
32. caused_by: идентификатор RFC, ответственного за инцидент;
33. close_code: идентификатор разрешения инцидента;
34. resolved_by: идентификатор пользователя, решившего инцидент;
35. resolved_at: дата и время решения инцидента пользователем (зависимая переменная);
36. closed_at: дата и время закрытия инцидента пользователя (зависимая переменная).

In [ ]:
# import kagglehub

# # Download latest version
# path = kagglehub.dataset_download("vipulshinde/incident-response-log")

# print("Path to dataset files:", path)

c:\Users\Admin\Documents\Python\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\Admin\.cache\kagglehub\datasets\vipulshinde\incident-response-log\2.archive...

100%|██████████| 2.07M/2.07M [00:00<00:00, 2.78MB/s]

Extracting files...

Path to dataset files: C:\Users\Admin\.cache\kagglehub\datasets\vipulshinde\incident-response-log\versions\2

In [5]:
df = pd.read_csv('incident_event_log.csv', sep=',')

In [6]:
df.head(3)

,number,incident_state,active,reassignment_count,reopen_count,sys_mod_count,made_sla,caller_id,opened_by,opened_at,...,u_priority_confirmation,notify,problem_id,rfc,vendor,caused_by,closed_code,resolved_by,resolved_at,closed_at
0,INC0000045,New,True,0,0,0,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
1,INC0000045,Resolved,True,0,0,2,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
2,INC0000045,Resolved,True,0,0,3,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00

### Обзор количественных переменных

In [7]:
df.dtypes

number                     object
incident_state             object
active                       bool
reassignment_count          int64
reopen_count                int64
sys_mod_count               int64
made_sla                     bool
caller_id                  object
opened_by                  object
opened_at                  object
sys_created_by             object
sys_created_at             object
sys_updated_by             object
sys_updated_at             object
contact_type               object
location                   object
category                   object
subcategory                object
u_symptom                  object
cmdb_ci                    object
impact                     object
urgency                    object
priority                   object
assignment_group           object
assigned_to                object
knowledge                    bool
u_priority_confirmation      bool
notify                     object
problem_id                 object
rfc                        object
vendor                     object
caused_by                  object
closed_code                object
resolved_by                object
resolved_at                object
closed_at                  object
dtype: object

In [8]:
df_num_features = df.select_dtypes(include=['float64', 'int64'])
df_num_features.head()

   reassignment_count  reopen_count  sys_mod_count
0                   0             0              0
1                   0             0              2
2                   0             0              3
3                   0             0              4
4                   0             0              0

In [9]:
df.describe()

       reassignment_count   reopen_count  sys_mod_count
count       119998.000000  119998.000000  119998.000000
mean             1.151236       0.021025       5.199312
std              1.782823       0.196173       7.804628
min              0.000000       0.000000       0.000000
25%              0.000000       0.000000       1.000000
50%              1.000000       0.000000       3.000000
75%              2.000000       0.000000       7.000000
max             27.000000       8.000000     129.000000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119998 entries, 0 to 119997
Data columns (total 36 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   number                   119998 non-null  object
 1   incident_state           119998 non-null  object
 2   active                   119998 non-null  bool
 3   reassignment_count       119998 non-null  int64
 4   reopen_count             119998 non-null  int64
 5   sys_mod_count            119998 non-null  int64
 6   made_sla                 119998 non-null  bool
 7   caller_id                119998 non-null  object
 8   opened_by                119998 non-null  object
 9   opened_at                119998 non-null  object
 10  sys_created_by           119998 non-null  object
 11  sys_created_at           119998 non-null  object
 12  sys_updated_by           119998 non-null  object
 13  sys_updated_at           119998 non-null  object
 14  contact_type             119998 non-null  object
 15  location                 119998 non-null  object
 16  category                 119998 non-null  object
 17  subcategory              119998 non-null  object
 18  u_symptom                119998 non-null  object
 19  cmdb_ci                  119998 non-null  object
 20  impact                   119998 non-null  object
 21  urgency                  119998 non-null  object
 22  priority                 119998 non-null  object
 23  assignment_group         119998 non-null  object
 24  assigned_to              119998 non-null  object
 25  knowledge                119998 non-null  bool
 26  u_priority_confirmation  119998 non-null  bool
 27  notify                   119998 non-null  object
 28  problem_id               119998 non-null  object
 29  rfc                      119998 non-null  object
 30  vendor                   119998 non-null  object
 31  caused_by                119998 non-null  object
 32  closed_code              119998 non-null  object
 33  resolved_by              119998 non-null  object
 34  resolved_at              119998 non-null  object
 35  closed_at                119998 non-null  object
dtypes: bool(4), int64(3), object(29)
memory usage: 29.8+ MB