In [2]:
# pip install kagglehub

In [3]:
import pandas as pd
import numpy as np
import matplotlib
import seaborn as sns
import sklearn

https://www.kaggle.com/datasets/vipulshinde/incident-response-log

Attribute Information:

1. number: идентификатор инцидента (24 918 различных значений);
2. incident state: восемь уровней, контролирующих переход процесса управления инцидентами от открытия к закрытию дела;
3. active: логический атрибут, показывающий, активна ли запись или закрыта/отменена;
4. reassignment_count: количество раз, когда в инциденте менялась группа или аналитики поддержки;
5. reopen_count: количество раз, когда решение инцидента было отклонено вызывающим абонентом;
6. sys_mod_count: количество обновлений инцидентов до этого момента;
7. made_sla: логический атрибут, показывающий, превысил ли инцидент целевой SLA;
8. caller_id: идентификатор затронутого пользователя;
9. opened_by: идентификатор пользователя, сообщившего об инциденте;
10. opened_at: дата и время открытия пользователя инцидента;
11. sys_created_by: идентификатор пользователя, зарегистрировавшего инцидент;
12. sys_created_at: дата и время создания системы инцидента;
13. sys_updated_by: идентификатор пользователя, обновившего инцидент и сгенерировавшего текущую запись журнала;
14. sys_updated_at: дата и время обновления системы инцидента;
15. contact_type: категориальный атрибут, показывающий, каким образом был сообщен инцидент;
16. location: идентификатор местоположения затронутого места;
17. category: описание затронутой услуги первого уровня;
18. subcategory: описание затронутой услуги второго уровня (относящееся к описанию первого уровня, т. е. к категории);
19. u_symptom: описание восприятия пользователем доступности услуги;
20. cmdb_ci: идентификатор (элемент подтверждения), используемый для сообщения о затронутом элементе (не обязательно);
21. impact: описание воздействия, вызванного инцидентом (значения: 1: Высокое; 2: Среднее; 3: Низкое);
22. urgency: описание срочности, о которой сообщил пользователь для разрешения инцидента (значения: 1: Высокая; 2: Средняя; 3: Низкая);
23. priority: рассчитывается системой на основе «воздействия» и «срочности»;
24. assignment_group: идентификатор группы поддержки, ответственной за инцидент;
25. assigned_to: идентификатор пользователя, ответственного за инцидент;
26. knowledge: логический атрибут, показывающий, использовался ли документ базы знаний для разрешения инцидента;
27. u_priority_confirmation: логический атрибут, показывающий, было ли дважды проверено поле приоритета;
28. notify: категориальный атрибут, показывающий, были ли сгенерированы уведомления об инциденте;
29. problem_id: идентификатор проблемы, связанной с инцидентом;
30. rfc: (запрос на изменение) идентификатор запроса на изменение, связанного с инцидентом;
31. vendor: идентификатор поставщика, ответственного за инцидент;
32. caused_by: идентификатор RFC, ответственного за инцидент;
33. close_code: идентификатор разрешения инцидента;
34. resolved_by: идентификатор пользователя, решившего инцидент;
35. resolved_at: дата и время решения инцидента пользователем (зависимая переменная);
36. closed_at: дата и время закрытия инцидента пользователя (зависимая переменная).

In [4]:
# import kagglehub

# # Download latest version
# path = kagglehub.dataset_download("vipulshinde/incident-response-log")

# print("Path to dataset files:", path)

In [5]:
df = pd.read_csv('data/incident_event_log.csv', na_values=['?']) # NaN замаскированы под "?"

C:\Users\Admin\AppData\Local\Temp\ipykernel_19764\2732078540.py:1: DtypeWarning: Columns (31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/incident_event_log.csv', na_values=['?']) # NaN замаскированы под "?"

In [6]:
df.head()

,number,incident_state,active,reassignment_count,reopen_count,sys_mod_count,made_sla,caller_id,opened_by,opened_at,...,u_priority_confirmation,notify,problem_id,rfc,vendor,caused_by,closed_code,resolved_by,resolved_at,closed_at
0,INC0000045,New,True,0,0,0,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,NaN,NaN,NaN,NaN,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
1,INC0000045,Resolved,True,0,0,2,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,NaN,NaN,NaN,NaN,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
2,INC0000045,Resolved,True,0,0,3,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,NaN,NaN,NaN,NaN,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
3,INC0000045,Closed,False,0,0,4,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,NaN,NaN,NaN,NaN,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
4,INC0000047,New,True,0,0,0,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,NaN,NaN,NaN,NaN,code 5,Resolved by 81,1/3/2016 09:52,6/3/2016 10:00

In [108]:
print(f'строк: {df.shape[0]}, столбцов: {df.shape[1]}')

строк: 119998, столбцов: 36

In [107]:
print(df['number'].count())
print(df['number'].nunique()) # уникальных

119998
20769

In [113]:
print(*df.columns, sep='\n')

number
incident_state
active
reassignment_count
reopen_count
sys_mod_count
made_sla
caller_id
opened_by
opened_at
sys_created_by
sys_created_at
sys_updated_by
sys_updated_at
contact_type
location
category
subcategory
u_symptom
cmdb_ci
impact
urgency
priority
assignment_group
assigned_to
knowledge
u_priority_confirmation
notify
problem_id
rfc
vendor
caused_by
closed_code
resolved_by
resolved_at
closed_at

In [ ]:
df = df.sort_values('sys_mod_count').drop_duplicates('number', keep='last') # оставляем последние записи по номеру

In [115]:
print(f'строк: {df.shape[0]}, столбцов: {df.shape[1]}')

строк: 20769, столбцов: 36

In [123]:
for col in ['opened_at', 'resolved_at', 'closed_at']:
    df[col] = pd.to_datetime(df[col], format='%d/%m/%Y %H:%M', errors='coerce')

In [124]:
df.head()

,number,incident_state,active,reassignment_count,reopen_count,sys_mod_count,made_sla,caller_id,opened_by,opened_at,...,u_priority_confirmation,notify,problem_id,rfc,vendor,caused_by,closed_code,resolved_by,resolved_at,closed_at
119997,INC0029233,New,True,0,0,0,True,Caller 3033,Opened by 17,2016-05-13 11:49:00,...,False,Do Not Notify,NaN,NaN,NaN,NaN,code 6,Resolved by 180,2016-05-17 16:46:00,2016-05-22 17:07:00
80800,INC0019250,Closed,False,0,0,1,True,Caller 2139,Opened by 108,2016-04-14 14:23:00,...,False,Do Not Notify,NaN,NaN,NaN,NaN,code 6,Resolved by 52,NaT,2016-04-19 15:07:00
55877,INC0012888,Closed,False,0,0,1,True,Caller 1393,Opened by 17,2016-03-30 09:28:00,...,False,Do Not Notify,NaN,NaN,NaN,NaN,code 1,Resolved by 11,NaT,2016-04-04 09:59:00
80994,INC0019296,Closed,False,0,0,1,True,Caller 1913,Opened by 62,2016-04-14 15:24:00,...,False,Do Not Notify,NaN,NaN,NaN,NaN,code 6,Resolved by 32,NaT,2016-04-19 16:07:00
56177,INC0012941,Closed,False,0,0,1,True,Caller 983,Opened by 17,2016-03-30 10:15:00,...,False,Do Not Notify,NaN,NaN,NaN,NaN,code 7,Resolved by 11,NaT,2016-04-04 10:59:00

In [126]:
df['made_sla'].value_counts(normalize=True)

made_sla
True     0.606433
False    0.393567
Name: proportion, dtype: float64

In [142]:
df['knowledge'].value_counts(normalize=True)

knowledge
False    0.829698
True     0.170302
Name: proportion, dtype: float64

In [132]:
df.select_dtypes(include='object').columns

Index(['number', 'incident_state', 'caller_id', 'opened_by', 'sys_created_by',
       'sys_created_at', 'sys_updated_by', 'sys_updated_at', 'contact_type',
       'location', 'category', 'subcategory', 'u_symptom', 'cmdb_ci', 'impact',
       'urgency', 'priority', 'assignment_group', 'assigned_to', 'notify',
       'problem_id', 'rfc', 'vendor', 'caused_by', 'closed_code',
       'resolved_by'],
      dtype='object')

In [140]:
df['assignment_group'].value_counts()

assignment_group
Group 70    7369
Group 25    1080
Group 39     995
Group 24     907
Group 23     745
            ...
Group 67       6
Group 2        5
Group 32       4
Group 36       2
Group 71       1
Name: count, Length: 64, dtype: int64

In [117]:
df.isna().sum()

number                         0
incident_state                 0
active                         0
reassignment_count             0
reopen_count                   0
sys_mod_count                  0
made_sla                       0
caller_id                      3
opened_by                    714
opened_at                      0
sys_created_by              9079
sys_created_at              9079
sys_updated_by                 0
sys_updated_at                 0
contact_type                   0
location                       6
category                       7
subcategory                    8
u_symptom                   4931
cmdb_ci                    20717
impact                         0
urgency                        0
priority                       0
assignment_group            2157
assigned_to                  716
knowledge                      0
u_priority_confirmation        0
notify                         0
problem_id                 20445
rfc                        20612
vendor                     20762
caused_by                  20767
closed_code                   81
resolved_by                   89
resolved_at                 1418
closed_at                      0
dtype: int64

### Обзор количественных переменных

In [11]:
df_num_features = df.select_dtypes(include=['float64', 'int64'])
df_num_features.head()

   reassignment_count  reopen_count  sys_mod_count
0                   0             0              0
1                   0             0              2
2                   0             0              3
3                   0             0              4
4                   0             0              0

In [106]:
df.describe().T

                       count      mean       std  min  25%  50%  75%    max
reassignment_count  119998.0  1.151236  1.782823  0.0  0.0  1.0  2.0   27.0
reopen_count        119998.0  0.021025  0.196173  0.0  0.0  0.0  0.0    8.0
sys_mod_count       119998.0  5.199312  7.804628  0.0  1.0  3.0  7.0  129.0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119998 entries, 0 to 119997
Data columns (total 36 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   number                   119998 non-null  object
 1   incident_state           119998 non-null  object
 2   active                   119998 non-null  bool
 3   reassignment_count       119998 non-null  int64
 4   reopen_count             119998 non-null  int64
 5   sys_mod_count            119998 non-null  int64
 6   made_sla                 119998 non-null  bool
 7   caller_id                119969 non-null  object
 8   opened_by                115163 non-null  object
 9   opened_at                119998 non-null  object
 10  sys_created_by           77644 non-null   object
 11  sys_created_at           77644 non-null   object
 12  sys_updated_by           119998 non-null  object
 13  sys_updated_at           119998 non-null  object
 14  contact_type             119998 non-null  object
 15  location                 119922 non-null  object
 16  category                 119934 non-null  object
 17  subcategory              119901 non-null  object
 18  u_symptom                91727 non-null   object
 19  cmdb_ci                  436 non-null     object
 20  impact                   119998 non-null  object
 21  urgency                  119998 non-null  object
 22  priority                 119998 non-null  object
 23  assignment_group         105785 non-null  object
 24  assigned_to              96968 non-null   object
 25  knowledge                119998 non-null  bool
 26  u_priority_confirmation  119998 non-null  bool
 27  notify                   119998 non-null  object
 28  problem_id               1937 non-null    object
 29  rfc                      882 non-null     object
 30  vendor                   182 non-null     object
 31  caused_by                18 non-null      object
 32  closed_code              119473 non-null  object
 33  resolved_by              119796 non-null  object
 34  resolved_at              117137 non-null  object
 35  closed_at                119998 non-null  object
dtypes: bool(4), int64(3), object(29)
memory usage: 29.8+ MB